### ISSUE TITLE
"@"

### ISSUE THREAD

**Issue by conal** [nikivazou/EquationalReasoningInLiquidHaskell#5]
Section 3 (Totality and Termination) contains "@" in a few places where I think backtick was intended. For instance, "Generally, a termination argument is of the form @/ [e1, ..., en]@. The expressions @ei@ ...". Maybe a bug in the conversion from LaTeX or Haddock.

**Comment by nikivazou** [comment]
Yes, fixed that too! Indeed a bug in the *manual* conversion from LaTeX.
